name: expense
networks:
  default:
    name: expense
volumes:
  mysql:
    external: true
services:
  mysql:
    image: mysql:1.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ExpenseApp@1 
      - MYSQL_USER=expense 
      - MYSQL_PASSWORD=ExpenseApp@1 
      - MYSQL_DATABASE=transactions
    volumes:
      - mysql:/var/lib/mysql

  backend:
    image: backend:1.0
    container_name: backend
    #command: sh -c "sleep20 && node /app/index.js"
    command: sh -c "sleep 20 && node /app/index.js"
    depends_on:
      - mysql

  frontend:
    image: frontend:1.0
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 80:80








  